using Credfeto.Version.Information.Generator.Builders;

namespace Credfeto.Version.Information.Generator.Helpers;

internal static class FileHeaderExtensions
{
    public static CodeBuilder AppendFileHeader(this CodeBuilder source)
    {
        return source.AppendLine("//------------------------------------------------------------------------------")
                     .AppendLine("// <auto-generated>")
                     .AppendLine("// This code was generated by a tool.")
                     .AppendLine("// Runtime Version: Current")
                     .AppendLine("//")
                     .AppendLine("// Changes to this file may cause incorrect behavior and will be lost if")
                     .AppendLine("// the code is regenerated.")
                     .AppendLine("// </auto-generated>")
                     .AppendLine("//------------------------------------------------------------------------------")
                     .AppendBlankLine();
    }
}