using System;
using Credfeto.Version.Information.Generator.Builders;
using FunFair.Test.Common;
using Microsoft.CodeAnalysis.Text;
using Xunit;

namespace Credfeto.Version.Information.Generator.Tests.Builders;

public sealed class CodeBuilderTests : TestBase
{
    [Fact]
    public void AppendLineWithContentAppendsText()
    {
        CodeBuilder builder = new();
        builder.AppendLine("hello world");
        string text = builder.Text.ToString();
        Assert.Contains("hello world", text, StringComparison.Ordinal);
    }

    [Fact]
    public void AppendLineWithWhitespaceAppendsBlankLine()
    {
        CodeBuilder builder = new();
        builder.AppendLine("first");
        builder.AppendLine("   ");
        builder.AppendLine("second");
        string text = builder.Text.ToString();
        Assert.Contains("first", text, StringComparison.Ordinal);
        Assert.Contains("second", text, StringComparison.Ordinal);
    }

    [Fact]
    public void AppendLineWithEmptyStringAppendsBlankLine()
    {
        CodeBuilder builder = new();
        builder.AppendLine("first");
        builder.AppendLine(string.Empty);
        builder.AppendLine("second");
        string text = builder.Text.ToString();
        Assert.Contains("first", text, StringComparison.Ordinal);
        Assert.Contains("second", text, StringComparison.Ordinal);
    }

    [Fact]
    public void AppendBlankLineAddsNewline()
    {
        CodeBuilder builder = new();
        builder.AppendBlankLine();
        string text = builder.Text.ToString();
        Assert.NotEmpty(text);
    }

    [Fact]
    public void AppendFileHeaderContainsAutoGeneratedMarker()
    {
        CodeBuilder builder = new();
        builder.AppendFileHeader();
        string text = builder.Text.ToString();
        Assert.Contains(
            "//------------------------------------------------------------------------------",
            text,
            StringComparison.Ordinal
        );
        Assert.Contains("<auto-generated>", text, StringComparison.Ordinal);
    }

    [Fact]
    public void AppendGeneratedCodeAttributeContainsGeneratedCode()
    {
        CodeBuilder builder = new();
        builder.AppendGeneratedCodeAttribute();
        string text = builder.Text.ToString();
        Assert.Contains("[GeneratedCode(", text, StringComparison.Ordinal);
    }

    [Fact]
    public void StartBlockDefaultBracesInsertsOpenAndCloseWithContent()
    {
        CodeBuilder builder = new();

        using (builder.StartBlock("namespace Foo"))
        {
            builder.AppendLine("class Bar { }");
        }

        string text = builder.Text.ToString();
        Assert.Contains("namespace Foo", text, StringComparison.Ordinal);
        Assert.Contains("{", text, StringComparison.Ordinal);
        Assert.Contains("class Bar { }", text, StringComparison.Ordinal);
        Assert.Contains("}", text, StringComparison.Ordinal);
    }

    [Fact]
    public void StartBlockDefaultBracesIndentsContent()
    {
        CodeBuilder builder = new();

        using (builder.StartBlock("namespace Foo"))
        {
            builder.AppendLine("class Bar { }");
        }

        string text = builder.Text.ToString();
        int namespaceIndex = text.IndexOf("namespace Foo", StringComparison.Ordinal);
        int classIndex = text.IndexOf("class Bar", StringComparison.Ordinal);
        Assert.True(namespaceIndex >= 0, "namespace Foo should be present in generated text");
        Assert.True(classIndex > namespaceIndex, "class Bar should appear after namespace Foo");

        int lineStart = text.LastIndexOf('\n', classIndex) + 1;
        string indentPart = text[lineStart..classIndex];
        Assert.True(indentPart.Length > 0, "Content inside block should be indented");
    }

    [Fact]
    public void StartBlockCustomMarkersUsesProvidedMarkers()
    {
        CodeBuilder builder = new();

        using (builder.StartBlock("module Foo", start: "begin", end: "end"))
        {
            builder.AppendLine("let x = 1");
        }

        string text = builder.Text.ToString();
        Assert.Contains("module Foo", text, StringComparison.Ordinal);
        Assert.Contains("begin", text, StringComparison.Ordinal);
        Assert.Contains("let x = 1", text, StringComparison.Ordinal);
        Assert.Contains("end", text, StringComparison.Ordinal);
    }

    [Fact]
    public void TextPropertyReturnsSourceText()
    {
        CodeBuilder builder = new();
        builder.AppendLine("public class Foo { }");
        SourceText text = builder.Text;
        Assert.NotNull(text);
        Assert.Contains("public class Foo { }", text.ToString(), StringComparison.Ordinal);
    }

    [Fact]
    public void NestedStartBlocksIndentCorrectly()
    {
        CodeBuilder builder = new();

        using (builder.StartBlock("namespace Foo"))
        {
            using (builder.StartBlock("public class Bar"))
            {
                builder.AppendLine("public int Value;");
            }
        }

        string text = builder.Text.ToString();
        Assert.Contains("namespace Foo", text, StringComparison.Ordinal);
        Assert.Contains("public class Bar", text, StringComparison.Ordinal);
        Assert.Contains("public int Value;", text, StringComparison.Ordinal);

        int valueIndex = text.IndexOf("public int Value;", StringComparison.Ordinal);
        int lineStart = text.LastIndexOf('\n', valueIndex) + 1;
        string indentPart = text[lineStart..valueIndex];
        Assert.True(indentPart.Length >= 8, "Doubly-nested content should have at least 8 spaces indent");
    }

    [Fact]
    public void DisposeDecreasesIndentAfterBlock()
    {
        CodeBuilder builder = new();

        using (builder.StartBlock("namespace Foo"))
        {
            builder.AppendLine("class Bar { }");
        }

        builder.AppendLine("// after block");
        string text = builder.Text.ToString();

        int afterIndex = text.IndexOf("// after block", StringComparison.Ordinal);
        int lineStart = text.LastIndexOf('\n', afterIndex) + 1;
        string indentPart = text[lineStart..afterIndex];
        Assert.True(indentPart.Length == 0, "Content after closed block should not be indented");
    }
}
